# Generated by Django 3.1.1 on 2020-09-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('n', models.IntegerField()),
                ('operation', models.CharField(choices=[('nearest', 'Nearest'), ('furthest', 'Furthest')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
