# Generated by Django 3.1.1 on 2020-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_coordinatesrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatesrequest',
            name='coordinates',
            field=models.ManyToManyField(blank=True, to='geo.Coordinate'),
        ),
    ]
